version: '3.1'
services:
  app:
    container_name: web_server
    build: 
      context: ./
    depends_on:
      - db
    ports:
      - "3001:3001"
    restart: on-failure:5

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: basedatos
    volumes:
      - "./DB.sql:/docker-entrypoint-initdb.d/database.sql"
    restart: always