version: '3.1'
services:
  app:
    image: app
    container_name: web_server
    build: 
      context: ./
    depends_on:
      - db
    ports:
      - "3001:3001"
    

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: basedatos
    volumes:
      - "./DB.sql:/docker-entrypoint-initdb.d/database.sql"
    restart: always